ROOTDIR = ../../..
STATIC_LIBRARY = gpu-ctm
FILES = ctmruntime ctmstream
EXTRAINCLUDEDIR = $(CTM_HOME)/libraries/amucgen $(CTM_HOME)/libraries/amuabi $(CTM_HOME)/libraries/amuisa $(CTM_HOME)/libraries/amucbuf $(CTM_HOME)/../../include
LIBRARIES = $(CTM_HOME)/../../bin/amucbuf $(CTM_HOME)/../../bin/amuisa $(CTM_HOME)/../../bin/amuAsm $(CTM_HOME)/../../bin/amucomp $(CTM_HOME)/../../bin/atictm 

include ../../../common.mk
