ROOTDIR := ../..
REGRESSIONDIRS := toy read_write sum input_output gather_direct \
                  gather_dependent accumulate reduce_basic reducetostream \
                  scatter indexof iterator gatherop convert_iter_to_stream \
                  iterator_dimensions replication_stride \
		  indexof_output infinite

SUBDIRS := $(REGRESSIONDIRS) reduce struct_input struct_gather multiple_output struct_output

include $(ROOTDIR)/common.mk
