ROOTDIR := ../..
REGRESSIONDIRS := toy read_write sum input_output gather_direct \
                  gather_dependent accumulate reduce_basic reducetostream \
                  scatter indexof iterator gatherop convert_iter_to_stream \
                  iterator_dimensions replication_stride pack_vout

SUBDIRS := $(REGRESSIONDIRS) reduce 

include $(ROOTDIR)/common.mk
