
ROOTDIR = ../../..
STATIC_LIBRARY = gles
FILES = glescontext glesstream glestexture gleskernel \
	gleswindow glesruntime \
	glesfunc glescheckgl gleswritequery

#SUBDIRS := GL

include ../../../common.mk

