ROOTDIR = ../..
STATIC_LIBRARY = brccsplitting
FILES = splittree splitnode splitbuilder splittraversal splittypes splitcompiler splitcompilercg splitcompilerhlsl splitdominator

include ../../common.mk
