ROOTDIR = ../../..
EXECUTABLE = rapid_collide
FILES = simple_rapid rapid_test prapid vector3 pbuild matrix3 peigen
CFLAGS = -Icollide
LIBRARIES = $(RUNTIME_LIBS)
BRCCFLAGS = -k
include $(ROOTDIR)/common.mk

