ROOTDIR = ../../..
EXECUTABLE = rapid_collide
FILES = rapid collide_test prapid vector3 pbuild matrix3 peigen plyload voutfloatN vout1dfloatN
#FILES = simple_rapid rapid_test prapid vector3 pbuild matrix3 peigen plyload
CFLAGS = -Icsgeom
LIBRARIES = $(RUNTIME_LIBS)
BRCCFLAGS =  
include $(ROOTDIR)/common.mk

