ROOTDIR = ../../..
EXECUTABLE = multibackend
FILES = multibackend main
LIBRARIES = $(RUNTIME_LIBS)

include $(ROOTDIR)/common.mk

#CFLAGS +=  -O3 -mfpmath=sse -ffast-math 
#CFLAGS +=  /O2 /RTC1- /arch:SSE /fp:fast 
