ROOTDIR = ../../..
EXECUTABLE = timing_vout
FILES = volume_division_hack vol_div tess writepng graphics tessellate voutHackfloatN vout1dfloatN timing raw_vout
LIBRARIES = $(RUNTIME_LIBS)
BRCCFLAGS = 

include $(ROOTDIR)/common.mk

