ROOTDIR = ../../..
EXECUTABLE = timing_vout
FILES = timing_rapid rapid collide_test volume_division_hack vol_div tess writepng graphics tessellate voutHackfloatN vout1dfloatN timing raw_vout matrix3 pbuild peigen plyload prapid vector3
LIBRARIES = $(RUNTIME_LIBS)
CFLAGS = -Icsgeom
BRCCFLAGS = 

include $(ROOTDIR)/common.mk

