ROOTDIR := ..
REGRESSIONDIRS := toy read_write sum input_output gather_direct \
                  gather_dependent accumulate reduce_basic reducetostream \
		  scatter indexof iterator gatherop

SUBDIRS := $(REGRESSIONDIRS) benchmark reduce csrMatvec

include $(ROOTDIR)/common.mk
