ROOTDIR := ..
SUBDIRS := toy read_write sum input_output gather_direct gather_dependent accumulate
REGRESSIONDIRS := toy read_write sum input_output gather_direct gather_dependent accumulate

include ../common.mk





