
ROOTDIR = ../..
STATIC_LIBRARY = nv30gl

GLFILES = glfunc gliter glkernel glstream glwindow glcheckgl glruntime
NV30FILES = nv30glruntime nv30glkernel
ARBFILES = arbruntime arbkernel

FILES = $(GLFILES) $(NV30FILES) $(ARBFILES)

include ../../common.mk
