
ROOTDIR = ../..
STATIC_LIBRARY = nv30gl

GLFILES = glfunc gliter glkernel glstream glwindow glcheckgl glruntime
NV30FILES = nv30glkernel nv30glruntime

FILES = $(GLFILES) $(NV30FILES)

include ../../common.mk
