#include "nv30gl.hpp"

using namespace brook;

PFNGLACTIVETEXTUREARBPROC       brook::glActiveTextureARB;
PFNGLGENPROGRAMSNVPROC          brook::glGenProgramsNV;
PFNGLLOADPROGRAMNVPROC          brook::glLoadProgramNV;
PFNGLBINDPROGRAMNVPROC          brook::glBindProgramNV;
PFNGLPROGRAMNAMEDPARAMETER4FNVPROC  brook::glProgramNamedParameter4fNV;
PFNGLMULTITEXCOORD2FARBPROC     brook::glMultiTexCoord2fARB;
PFNGLMULTITEXCOORD4FARBPROC     brook::glMultiTexCoord4fARB;

#ifdef WIN32

PFNWGLCREATEPBUFFERARBPROC      brook::wglCreatePbufferARB;
PFNWGLGETPBUFFERDCARBPROC       brook::wglGetPbufferDCARB;
PFNWGLCHOOSEPIXELFORMATARBPROC  brook::wglChoosePixelFormatARB;
PFNWGLBINDTEXIMAGEARBPROC       brook::wglBindTexImageARB;
PFNWGLRELEASETEXIMAGEARBPROC    brook::wglReleaseTexImageARB;

#define   XXX(B,A) A = (B) wglGetProcAddress(#A); assert(A);
#else

PFNGLXCHOOSEFBCONFIGSGIX        brook::glXChooseFBConfigSGIX;
PFNGLXDESTROYGLXPBUFFERSGIX     brook::glXDestroyGLXPbufferSGIX;
PFNGLXCREATECONTEXTWITHCONFIGSGIX  brook::glXCreateContextWithConfigSGIX;

#define   XXX(B,A) A = (B) glxGetProcAddress(#A); assert(A);
#endif


void brook::initglfunc(void) {
#if WIN32
   XXX(PFNWGLCREATEPBUFFERARBPROC,     wglCreatePbufferARB);
   XXX(PFNWGLGETPBUFFERDCARBPROC,      wglGetPbufferDCARB);
   XXX(PFNWGLCHOOSEPIXELFORMATARBPROC, wglChoosePixelFormatARB);
   XXX(PFNWGLBINDTEXIMAGEARBPROC,      wglBindTexImageARB);
   XXX(PFNWGLRELEASETEXIMAGEARBPROC,   wglReleaseTexImageARB);
#else
   XXX(PFNGLXCHOOSEFBCONFIGSGIX,       glXChooseFBConfigSGIX);
   XXX(PFNGLXDESTROYGLXPBUFFERSGIX,    glXDestroyGLXPbufferSGIX;
   XXX(PFNGLXCREATECONTEXTWITHCONFIGSGIX, glXCreateContextWithConfigSGIX);
#endif

   XXX(PFNGLACTIVETEXTUREARBPROC,      glActiveTextureARB);
   XXX(PFNGLGENPROGRAMSNVPROC,         glGenProgramsNV);
   XXX(PFNGLLOADPROGRAMNVPROC,         glLoadProgramNV);
   XXX(PFNGLBINDPROGRAMNVPROC,         glBindProgramNV);
   XXX(PFNGLPROGRAMNAMEDPARAMETER4FNVPROC, glProgramNamedParameter4fNV);
   XXX(PFNGLMULTITEXCOORD2FARBPROC,    glMultiTexCoord2fARB);
   XXX(PFNGLMULTITEXCOORD4FARBPROC,    glMultiTexCoord4fARB);
}

