ROOTDIR = ../../..
EXECUTABLE = gflops
FILES = gflops timer
LIBRARIES = $(RUNTIME_LIBS)

include $(ROOTDIR)/common.mk

#CFLAGS +=  -O3 -mfpmath=sse -ffast-math 
#CFLAGS += -fopenmp 
#LDFLAGS +=  -lgomp 

#CFLAGS +=  /O2 /arch:SSE2 /GS- /fp:fast 
#CFLAGS += /openmp 

