
ROOTDIR = ../../..
STATIC_LIBRARY = ogl
FILES = oglcontext oglstream ogltexture oglkernel \
	oglwindow aticontext nvcontext oglruntime \
	oglfunc oglcheckgl oglwritequery

include ../../../common.mk

