ROOTDIR = ../../..
EXECUTABLE = particle_cloth
FILES = particle_cloth particle_cloth_cpu particle_cloth_mout timing main particle_cloth_split
LIBRARIES = $(RUNTIME_LIBS)
BRCCFLAGS = 

include $(ROOTDIR)/common.mk

