ROOTDIR := ../../..

REGRESSIONDIRS := at_indexof_output at_output_domain at_indexof_stream at_stream_fetch at_stream_domain \
	at_gather_fetch at_gather_domain

SUBDIRS := $(REGRESSIONDIRS)

include $(ROOTDIR)/common.mk

